### ISSUE TITLE
KNMI Plugin misses data

### ISSUE THREAD

**Issue by After-burner** [bramvreugd/Domoticz-KNMI-Weather-Plugin#1]
Hi Bram,

Compliments for your KNMI Plugin for Domoticz. Small issue on my side. Actually I installed the plugin to get the Max en Min temp for TODAY. It is in the parameterlist from the API but appearently you didn't implement those two parameters.

Could you do so for the next update of this plugin please.

Sake Kingma

**Comment by bramvreugd** [comment]
That should be no problem. Unfortunatelly my  domoticz crashed yesterday so I must relair that first.Op 22 jan. 2023 22:09 schreef After-burner ***@***.***>:
Hi Bram,
Compliments for your KNMI Plugin for Domoticz. Small issue on my side. Actually I installed the plugin to get the Max en Min temp for TODAY. It is in the parameterlist from the API but appearently you didn't implement those two parameters.
Could you do so for the next update of this plugin please.
Sake Kingma

**Comment by bramvreugd** [comment]
Done

**Comment by edwinp1** [comment]
Thx a lot!!!

Kind Regards

Edwin
