### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by edwinp1** [bramvreugd/Domoticz-KNMI-Weather-Plugin#2]
Hi Bram,

Compliments for your KNMI Plugin for Domoticz. Works wonderfull.
I saw on the weerlive website that there is a new API, and the website specifies: de oude 1.0-API wordt uitgefaseerd en blijft tot 31 december 2025 beschikbaar [op dit endpoint.](https://weerlive.nl/api/json-data-10min.php?key=demo&locatie=Amsterdam) Gebruik je oudere HomeAssistant/Homey/Domoticz- of andere software, start dan met dit endpoint tot de ontwikkelaar de app heeft aangepast aan de nieuwe API.

Have you seen this, and are you able update the plugin? 

Kind regards

Edwin

**Comment by bramvreugd** [comment]
Edwin,

That should not be that difficult. 
Do you need all the five days weather forecast?
And what to do with the 24 hour forecast.

Best regards 
Bram

**Comment by edwinp1** [comment]
Hi Bram,

Right now the only thing that I am using is whats in the "old" or current plugin.
So just an update with all the current devices:
Name="Temperatuur"
Name="Verwachting"
Name="Wind"
Name="Min temp morgen"
Name="Max temp morgen"
Name="Wind morgen"                                                        
Name="Wind overmorgen"
Name="Regen morgen"
Name="Zon morgen"
Name="Zon":
Name="Alarm"
Name="Dauwpunt":
Name="Zicht"
Name="Min temp overmorgen"
Name="Max temp overmorgen"
Name="Regen overmorgen"
Name="Zon overmorgen"
Name="Min temp")
Name="Max temp"

Will do it for me, maybe you can add GR = Globale (zonne)straling ??
I tried editing the plugin.py file with for the new API myself, but could not backward engineer it all, and failed.

So I'm looking forward to what you can do!!

Kind Regards

Edwin

**Comment by bramvreugd** [comment]
Api is modified.
Globale (zonne)straling added

Please comment is is does not work well for you.

Kind regards,
Bram Vreugdenhil

**Comment by edwinp1** [comment]
Thx a Lot

Op wo 10 apr 2024 om 15:04 schreef bramvreugd ***@***.***>:
